### ISSUE TITLE
Including the src directory in build products results in IE11 syntax error

### ISSUE THREAD

**Issue by monkeystacker** [kisenka/svg-baker#20]
Including es2015 javascript files in the src directory as part of the build products results in IE11 syntax error when everything is compiled by babel due to use of 'class'.  If this is removed then everything works fine in IE11

**Comment by kisenka** [comment]
I did't get, please explain what you're doing and what you expect

**Comment by monkeystacker** [comment]
Sorry i meant to leave this issue on the svg-baker-runtime project I will create the same issue there

**Comment by kisenka** [comment]
Ah, I get it. Thanks.
