### ISSUE TITLE
<symbol> elements shouldn't be self-closing

### ISSUE THREAD

**Issue by ShimShamSam** [kisenka/svg-baker#7]
Edge is throwing a warning that the &lt;symbol> tag should have a corresponding &lt;/symbol> element instead of being self-closing. The examples found at [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol) seem to agree.

**Comment by kisenka** [comment]
Where did you find self-closing symbols?

**Comment by ShimShamSam** [comment]
So sorry, this actually relates to svgo
